
# library(arules)
# library(arulesSequences)
# library(stringr)
# library(Hmisc)
# library(corrr)
# library(fpc)
# library(NbClust)
# 
# library(tidyverse)

# source('./clustering/clustering_methods.R', chdir=TRUE)
# source('./clustering/cluster_visualization.R', chdir=TRUE)
# source('./general/basic_stats.R', chdir=TRUE)
# source('./general/correlations.R', chdir=TRUE)
# source('./general/dates.R', chdir=TRUE)
# source('./general/model_measurements.R', chdir=TRUE)
# source('./general/outliers.R', chdir=TRUE)
# source('./general/utilities.R', chdir=TRUE)
# source('./output/logger.R', chdir=TRUE)
# source('./output/markdown.R', chdir=TRUE)
# source('./output/output.R', chdir=TRUE)
# source('./output/plots.R', chdir=TRUE)
# source('./probability/bayes.R', chdir=TRUE)
# source('./probability/decision_analysis.R', chdir=TRUE)
# source('./probability/inference.R', chdir=TRUE)
# source('./pattern_recognition/apriori.R', chdir=TRUE)
# source('./pattern_recognition/apriori_sequence.R', chdir=TRUE)
# source('./testing/test_helpers.R', chdir=TRUE)
