library('testthat')
library('readr')
source('../output/markdown.R', chdir=TRUE)

#to run from command line, use:
#library('testthat')
# test_file("test_markdown.R")

test_that("output: markdown", {
	markdown_file = '../output/example_markdown.md'
	
	sink(file=markdown_file, append=FALSE) # should automatically delete file if it exists (which it should because we keep it for an example)
	cat(paste('generated by ', urlm('test_markdown.R', '../tests/test_markdown.R', postfix='\n\n')))
	cat(h1('header 1', postfix='\n'))
	cat('text\n')
	cat(h2('header 2', postfix='\n'))
	cat('text\n')
	cat(h3('header 3', postfix='\n'))
	cat('text\n')

	cat(sprintf('%s %s %s %s %s %s %s %s\n\n', 'this is some', bold('bold text'), 'and this is some', ital('italicized text'), 'and this is some', strike('strike-through text'), 'and this some', code('inline code')))
	cat(codeb('and here is some\nblock code',postfix='\n\n'))
	cat(codeb('document.getElementById(\'demo\').style.fontSize=\'35px\'', syntax='javascript',postfix='\n\n'))
	cat(blockq('this is a blockquote', postfix='\n\n'))

	vector1 = seq(from=0, to=100, by=1)
	vector2 = seq(from=100, to=0, by=-1)
	percentile_matrix = create_percentile_matrix(list_of_datasets=list(vector1, vector2), c('test1', 'test2'))
	cat(table_matrix(a_matrix=percentile_matrix, title='example table from matrix', title_format=h3, postfix='\n'))
	cat('and blow is a code block using `codebc` which calls `print_c` in [output.R](./output.R) to preserve `print()`-like formatting:\n') # add this to test formatting (something after matrix)
	cat(codebc(summary(percentile_matrix), postfix = '\n\n'))
	cat(sprintf('%s%s%s\n\n', 'and here is a ', urlm('url', '../README.md'), ' to the readme file'))
	cat('and here is an image:\n\n')
	cat(image(text='the image', url='../readme/kmeans_5_clusters.png', postfix='\n\n'))
	cat('the end :)\n') # add this to test formatting (something after matrix)
	sink() # remove sink

	test_file_text = read_file(markdown_file)
	expect_that(nchar(test_file_text), equals(2731))
})

test_that("output: table_matrix", {
	# table_matrix function should require a row_header, otherwise the format will be messed up when rendering in markdown file (i.e. Github is messed up, although Atom editor is not.)

	# first test normal (default variables) workflow works.
	vector1 = seq(from=0, to=100, by=1)
	vector2 = seq(from=100, to=0, by=-1)
	percentile_matrix = create_percentile_matrix(list_of_datasets=list(vector1, vector2), c('test1', 'test2'))
	possibleError_expect_no_error = tryCatch(table_matrix(a_matrix=percentile_matrix), error=function(e) e)
	expect_false(inherits(possibleError_expect_no_error, 'error'))

	# test error when passing in blank header
	possibleError_expect_error_empty = tryCatch(table_matrix(a_matrix=percentile_matrix, row_header=''), error=function(e) e)
	expect_true(inherits(possibleError_expect_error_empty, 'error'))
	expect_that(possibleError_expect_error_empty$message, equals('cannot pass in empty/NULL row_header'))

	# test error when passing in NULL header
	possibleError_expect_error_null = tryCatch(table_matrix(a_matrix=percentile_matrix, row_header=NULL), error=function(e) e)
	expect_true(inherits(possibleError_expect_error_null, 'error'))
	expect_that(possibleError_expect_error_null$message, equals('cannot pass in empty/NULL row_header'))
})
